### ISSUE TITLE
Realse File missing 

### ISSUE THREAD

**Issue by isuruwelagedara** [shravan-d/SculptMate#4]
Release file can't find out ?

**Comment by benyaminrazian** [comment]
KeyError: 'bpy_prop_collection[key]: key "._FILENAME_" not found'
Traceback (most recent call last):
  File "C:\Users\benix\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderMalt\MaltNodes\MaltNodeTree.py", line 363, in track_library_changes
    def track_library_changes(force_update=False, is_initial_setup=False):

KeyboardInterrupt

**Comment by shravan-d** [comment]
> File "C:\Users\benix\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderMalt\MaltNodes\MaltNodeTree.py", line 363, in track_library_changes def track_library_changes(force_update=False, is_initial_setup=False):

From the error description you gave, it looks like this could be a problem with a different addon named BlenderMalt.
